name: OpenWrt 25.12 Builder

on:
  workflow_dispatch:
  repository_dispatch:
    types: [openwrt-25.12]

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-25.12
  TZ: Asia/Shanghai

jobs:
  OpenWrt_Builder:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        type:
          - router
          - gateway

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone ${{env.TZ}}
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Check space usage
        run: df -hT

      - name: Clone source code
        working-directory: /workdir
        run: |
          git clone -b ${{env.REPO_BRANCH}} --single-branch --depth 1 ${{env.REPO_URL}} openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: copy custom scripts
        run: |
          cp ${{env.REPO_BRANCH}}/${{matrix.type}}/* openwrt/
          chmod +x openwrt/*.sh

      - name: Load custom feeds
        run: |
          cd openwrt
          ./diy-part1-${{matrix.type}}.sh

      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          cd openwrt
          ./diy-part2-${{matrix.type}}.sh

      - name: Generate custom configuration
        run: |
          cd openwrt
          cp -f default.config .config
          make defconfig
          ./scripts/diffconfig.sh > immortalwrt-${{matrix.type}}-default.config

      - name: Upload default configuration to artifact
        uses: actions/upload-artifact@main
        with:
          name: immortalwrt-${{matrix.type}}-default.config
          path: openwrt/immortalwrt-${{matrix.type}}-default.config
          retention-days: 3

      - name: Download package
        id: package
        run: |
          cd openwrt
          make download -j $(($(nproc)+1))
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j$(($(nproc) + 1)) V=s || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "COMPILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV
          echo "COMPILE_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Check space usage
        run: df -hT

      - name: Organize compiled firmware
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cp -rf openwrt/immortalwrt-${{matrix.type}}-default.config openwrt/bin/targets/x86/64/
          cd openwrt/bin/targets/x86/64
          rm -rf *.buildinfo
          rm -rf profiles.json
          rm -rf sha256sums
          rm -rf packages
          rm -rf immortalwrt-x86-64-generic-kernel.bin
          rm -rf immortalwrt-x86-64-generic.manifest
          rm -rf immortalwrt-x86-64-generic-squashfs-rootfs.img.gz
          rm -rf immortalwrt-x86-64-generic-targz-combined-efi.img.gz
          rm -rf immortalwrt-x86-64-generic-targz-rootfs.img.gz
          rm -rf immortalwrt-x86-64-generic-targz-rootfs.tar.gz
          mv immortalwrt-x86-64-generic-rootfs.tar.gz immortalwrt-${{matrix.type}}-generic-rootfs-x86_64-25.12-${{env.COMPILE_TIME}}.tar.gz
          mv immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz immortalwrt-${{matrix.type}}-generic-squashfs-combined-efi-x86_64-25.12-${{env.COMPILE_TIME}}.img.gz

      - name: Upload firmware to release
        if: steps.compile.outputs.status == 'success' && !cancelled()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file_glob: true
          file: openwrt/bin/targets/x86/64/*
          tag: immortalwrt-25.12-${{env.COMPILE_DATE}}
          body: |
            # IP
            - immortalwrt-router: 192.168.3.1
            - immortalwrt-gateway: 192.168.1.5
            # username
            - root
            # password
            - password
          overwrite: true

  Delete_Workflow:
    needs: [OpenWrt_Builder]
    runs-on: ubuntu-24.04
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 2
